/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import communication.Operacija;
import communication.Zahtev;
import domain.Zaposleni;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import logic.FormaKontroler;
import logic.Kontroler;

/**
 *
 * @author Korisnik
 */
public class MainForm extends javax.swing.JFrame {
    
    Zaposleni user;

    /**
     * Creates new form MainForm
     */
    public MainForm(Zaposleni z) {
        initComponents();
        this.user = z;
        setTitle(z.getIme()+z.getPrezime());
        FormaKontroler.getInstance().setMforma(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSobe = new javax.swing.JMenuItem();
        menuGosti = new javax.swing.JMenuItem();
        menuRezervacije = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Uspešna prijava! ");

        jLabel2.setText("Dobrodošli u aplikaciju za upravljanje rezervacijama.");

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        menuSobe.setText("Sobe");
        menuSobe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobeActionPerformed(evt);
            }
        });
        jMenu1.add(menuSobe);

        menuGosti.setText("Gosti");
        menuGosti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGostiActionPerformed(evt);
            }
        });
        jMenu1.add(menuGosti);

        menuRezervacije.setText("Rezervacije");
        menuRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRezervacijeActionPerformed(evt);
            }
        });
        jMenu1.add(menuRezervacije);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGostiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGostiActionPerformed
        // TODO add your handling code here:
        GostiForm gosti = new GostiForm(this, false);
        gosti.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        gosti.pack();
        gosti.setLocationRelativeTo(null);
        gosti.setVisible(true);
    }//GEN-LAST:event_menuGostiActionPerformed

    private void menuSobeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobeActionPerformed
        // TODO add your handling code here:
        SobaForm sobe = new SobaForm(this, false);
        sobe.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        sobe.pack();
        sobe.setLocationRelativeTo(null);
        sobe.setVisible(true);
    }//GEN-LAST:event_menuSobeActionPerformed

    private void menuRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRezervacijeActionPerformed
        // TODO add your handling code here:
        RezervacijaForm forma = new RezervacijaForm(this, false, user);
        forma.pack();
        forma.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        forma.setLocationRelativeTo(null);
        forma.setVisible(true);
        
    }//GEN-LAST:event_menuRezervacijeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            Zahtev zahtev = new Zahtev(Operacija.LOGOUT, user);
            Kontroler.getInstance().createObject(zahtev);
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuGosti;
    private javax.swing.JMenuItem menuRezervacije;
    private javax.swing.JMenuItem menuSobe;
    // End of variables declaration//GEN-END:variables

    public void odjava() {
        try {
            Kontroler.getInstance().odjava();
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
