/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import com.sun.java.accessibility.util.SwingEventMonitor;
import communication.Operacija;
import communication.Zahtev;
import domain.Soba;
import form.model.SobaTableModel;
import form.thread.RoomThread;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import logic.FormaKontroler;
import logic.Kontroler;

/**
 *
 * @author Korisnik
 */
public class SobaForm extends javax.swing.JDialog {

    
    RoomThread nit = new RoomThread();
    private String lastFilterCriteria = null;
    private int lastResultCount = -1;
    private Timer messageTimer;
private final int MESSAGE_DELAY = 3000;

 private volatile boolean isFilteringActive = false;
    /**
     * Creates new form SobaForm
     */
    public SobaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        FormaKontroler.getInstance().setSforma(this);
        nit.setForma(this);
        nit.start();
        addDocumentListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTip = new javax.swing.JTextField();
        txtBrKreveta = new javax.swing.JTextField();
        txtCena = new javax.swing.JTextField();
        txtPogled = new javax.swing.JTextField();
        btnKreiraj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSobe = new javax.swing.JTable();
        btnPrikazi = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        comboDostupna = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tip:");

        jLabel2.setText("Broj Kreveta:");

        jLabel3.setText("Dostupna:");

        jLabel4.setText("Cena:");

        jLabel5.setText("Pogled:");

        btnKreiraj.setText("Kreiraj sobu");
        btnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajActionPerformed(evt);
            }
        });

        tblSobe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSobe);

        btnPrikazi.setText("Prikaži sobu");
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        comboDostupna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));

        jLabel6.setText("Filtriraj sobe po tipu:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTip)
                                    .addComponent(txtBrKreveta)
                                    .addComponent(txtCena, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(txtPogled)
                                    .addComponent(comboDostupna, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btnKreiraj)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addComponent(btnPrikazi, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFilter))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrikazi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBrKreveta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboDostupna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtPogled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreiraj)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajActionPerformed
        try {
            // TODO add your handling code here:
            Soba soba = new Soba();
            String broj = txtBrKreveta.getText().trim();
            try {
            int value = Integer.parseInt(broj);
            soba.setBrojKreveta(value);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Please enter a valid numeric value for br. kreveta.");
            return;
        }
            soba.setPogled(txtPogled.getText().trim());
            soba.setTip(txtTip.getText().trim());
            String cena = txtCena.getText().trim();
            try {
            double value = Double.parseDouble(cena);  
            soba.setCena(value);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Please enter a valid numeric value for cena.");
            return;
        }
            soba.setDostupna(Boolean.parseBoolean(comboDostupna.getSelectedItem().toString()));
            Zahtev zahtev = new Zahtev(Operacija.C_SOBA, soba);
            Kontroler.getInstance().createObject(zahtev);
        } catch (IOException ex) {
            Logger.getLogger(SobaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnKreirajActionPerformed

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
        // TODO add your handling code here:
        int pozicija = tblSobe.getSelectedRow();
        if(pozicija==-1){
        JOptionPane.showMessageDialog(null,"Sistem ne može da učita sobu. Izaberite polje forme" );
        return;
        }
        SobaTableModel tm = (SobaTableModel) tblSobe.getModel();
        Soba soba = tm.getSobe().get(pozicija);
        FormaKontroler.getInstance().getSforma().startShowForm(soba);
        JOptionPane.showMessageDialog(null, "Sistem je učitao sobu");

    }//GEN-LAST:event_btnPrikaziActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        nit.stopThread();
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SobaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SobaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SobaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SobaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SobaForm dialog = new SobaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JComboBox<String> comboDostupna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSobe;
    private javax.swing.JTextField txtBrKreveta;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtFilter;
    private javax.swing.JTextField txtPogled;
    private javax.swing.JTextField txtTip;
    // End of variables declaration//GEN-END:variables

 

    public void populateTable(List<Soba> sobe) {
         SobaTableModel tm = new SobaTableModel(sobe);
         tblSobe.setModel(tm);
    }

    public void startShowForm(Soba nova) {
         ShowRoom room = new ShowRoom(this, false, nova);
            room.pack();
            room.setLocationRelativeTo(null);
            room.setVisible(true);
    }

    private void addDocumentListeners() {
     txtFilter.getDocument().addDocumentListener(new DocumentListener() {
    @Override
    public void changedUpdate(DocumentEvent e) {
        runSearch();
    }
    @Override
    public void removeUpdate(DocumentEvent e) {
        runSearch();
    }
    @Override
    public void insertUpdate(DocumentEvent e) {
        runSearch();
    }
     private void runSearch() {
        SwingUtilities.invokeLater(() -> {
            try {
                String searchText = txtFilter.getText().trim();
                Zahtev zahtev = new Zahtev(Operacija.R_SOBA, searchText);
                Kontroler.getInstance().createObject(zahtev);
            } catch (IOException ex) {
                Logger.getLogger(SobaForm.class.getName()).log(Level.SEVERE, null, ex);
            }
                
               
               
        });
    }
     });}


    
    public void updateWithFilter(List<Soba> sobe) {
    
    isFilteringActive = true;

    SobaTableModel tm = new SobaTableModel(sobe);
    tblSobe.setModel(tm);
    String currentFilterCriteria = txtFilter.getText().trim();
    int currentResultCount = sobe.size();

    if (messageTimer != null && messageTimer.isRunning()) {
        messageTimer.stop();
    }

    messageTimer = new Timer(MESSAGE_DELAY, e -> {
        if (!currentFilterCriteria.equals(lastFilterCriteria) || currentResultCount != lastResultCount) {
            if (sobe.isEmpty()) {
                JOptionPane.showMessageDialog(tblSobe, "Sistem ne može da nađe sobe po zadatoj vrednosti.");
            } else {
                JOptionPane.showMessageDialog(tblSobe, "Sistem je našao sobe po zadatoj vrednosti.");
            }

           
            lastFilterCriteria = currentFilterCriteria;
            lastResultCount = currentResultCount;
        }
       
        isFilteringActive = currentFilterCriteria.isEmpty();
    });
    messageTimer.setRepeats(false);
    messageTimer.start();
}

    public void showDialogue(Soba soba) {
        if(soba==null){
        
            JOptionPane.showMessageDialog(null, "Sistem ne može da kreira sobu. Greške u validaciji");
            return;
        }
        
        JOptionPane.showMessageDialog(null, "Sistem je kreirao sobu!");
        
    }
    
    public boolean shouldUpdate() {
    return !isFilteringActive;
}
}
   


